config/routes.rb
Rails.application.routes.draw do

  resources :favorites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  root to: 'home#index'

  devise_for :users

  resources :user_cryptos
  resources :crypto_currencies, only: [:show]
  resources :cryptolist, only: [:show]

  resources :friend_requests, only: [:create]
  resources :friendships, only: [:create, :destroy]
  resources :profiles, only: [:index, :show, :update]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:show]
  resources :home, only: [:index]

  resources :news, only: [:index]
  resources :articles do
    resources :pictures, only: [:create]
  end
  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :admin, only: [:index, :show]


  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/terms_and_conditions'
  get 'static_pages/privacy_policy'

end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	belongs_to :tag
	has_many :comments
  has_one_attached :picture
  has_many :likes
  has_many :favorites, foreign_key: "favorite_article"
  has_many :interested_users, through: :favorites, foreign_key: "favorite_article"

  # Method that checks if the request of index comes from the research bar or from the navbar

  def self.check_if_research(research)
  	if research[:content] == nil || research[:content] == ""
  		return false
		else
			return true
		end
	end

	# Method that uses the content of research input to collect any article that contains it either in
	# its title, content, tag or author email.

	def self.make_research(research)
		unless research[:content] == nil
			@articles = []
			@find_articles = Article.all
			@find_articles.each do |article|
				if article.tag.name.include? research[:content]
					@articles.append(article)
				elsif article.user.email.include? research[:content]
					@articles.append(article)
				elsif article.content.include? research[:content]
					@articles.append(article)
				elsif article.title.downcase.include? research[:content]
					@articles.append(article)
				end
			end
			return @articles.reverse
		end
	end

	# Verifies if the tag attached to the created article does exist and creates it if not
	
	def self.tag_exists?(tag)
		if Tag.find_by(name: tag) == nil
			Tag.create(name: tag)
		end
	end
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show,:index]

	def index
		@research = params
		unless Article.check_if_research(@research)
			@articles = Article.all.reverse
		else
			@articles = Article.make_research(@research)
		end
	end

	def show
		@article = Article.find(params[:id])
		@tag = @article.tag
		@user = @article.user
		@comments = @article.comments
		if current_user
			current_user.articles.each do |article|
				if article == @article
						Comment.has_been_read?(@comments)
				end
			end
		end
	end

	def create
		Article.tag_exists?(params[:tag])
		@article = Article.create(
			title: params[:title],
			content: params[:content],
			user: current_user,
			tag: Tag.find_by(name: params[:tag])
		)
		@article.picture.attach(params[:picture])
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
		@tag = @article.tag.name
	end

	def update
		Article.tag_exists?(params[:tag])
		@article = Article.find(params[:id])
		puts params
		@article.update_attributes(
			:title => params[:title],
			:content => params[:content],
			:user => current_user,
			:tag => Tag.find_by(name: params[:tag])
			)

		if params[:picture]
			@article.picture.attach(params[:picture])
		end
		redirect_to articles_path
	end

	def destroy
		Article.find(params[:id]).destroy
		redirect_to articles_path
	end

end

app/views/articles/edit.html.erb
<div class="pages-container">
  <div class="space-bg">
    <h1 class="text-center edit-article-title">
      Edit article
    </h1>
    <div class="d-flex justify-content-center align-items-center sign-card-container">
      <div class="ttm-card-bg edit-user-card d-flex flex-column justify-content-center new-article-card">
        <%= form_tag url_for(action: "update"), method: "put" do %>
          <div class="form-group article-edit-form-inputs">
            <%= label_tag 'Title' %>
            <br/>
            <%= text_field_tag 'title', @article.title %>
          </div>
          <div class="form-group article-edit-form-inputs">
            <%= label_tag 'Content' %>
            <br>
            <%= text_area_tag 'content', @article.content %>
          </div>
          <div class="form-group article-edit-form-inputs">
            <%= label_tag 'Tag' %>
            <br>
            <%= text_field_tag 'tag', @tag %>
          </div>
            <%= submit_tag "Update article", class: "btn sign-ttm-btn update-article-btn" %>
          <% end %>
          <%= form_tag article_pictures_path(@article.id), multipart: true do %>
            <%= file_field_tag :picture %>
            <%= submit_tag "Update picture", class: "update-article-img-update" %>
          <% end %>

      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="pages-container">
	<div class="space-bg">
		<div class="news-container">
    		<h1 class="page-title text-center">
    			Articles
    		</h1>

			<div class="d-flex justify-content-between align-items-center articles-page-tools">
				<a class="btn sign-ttm-btn"
					<%= link_to "New article", new_article_path %>
				</a>

				<%= @hello %>
				<%= form_tag articles_path,class: "search-articles-form", :method => :get do %>
					<div class="d-flex justify-content-center align-content-center articles-search-form-elements">
						<%= text_field_tag 'content', "",class: "new-article-input-textarea" %>
						<%= submit_tag "Search article", class: "btn new-article-input-btn" %>
					</div>
				<% end %>
			</div>

			<div class="card-columns">
				<% unless @articles == nil %>
					<% @articles.each do |article| %>
						<div class="card ttm-card-bg article-cards">
							<h3 class="article-card-title">
								<%= link_to article.title, article_path(article.id) %>
							</h3>

							<% if article.picture.attached? %>
								<div class="article-card-img-container">
									<%= image_tag(article.picture, class: "article-show-img") %>
								</div>
							<% else %>
								<hr class="articles-card-hr">
							<% end %>

							<div class="article-card-bottom">
								<p>Author :</p>
								<p class="article-card-text"><%= link_to article.user.email, profile_path(article.user.id) %></p>
								<p class="article-card-text"><%= article.tag.name %></p>
							  <% if current_user %>
										<div class="d-flex">
										<div class="likes-container-container">
											<% @test = current_user.likes.find_by(article: article) %>
											<% unless @test %>
												<% if article.likes.length == 0 %>
													<%= link_to likes_path(:article => article.id), :method => :post do %>
														<div class="d-flex likes-container">
														<%= image_tag "Like.png", class: "like-icon" %>
															<p class="likes-number"> 0 </p>
														</div>
													<% end %>
													<br>
												<% else %>
													<%= link_to likes_path(:article => article.id), :method => :post do %>
														<div class="d-flex likes-container">
														<%= image_tag "Like.png", class: "like-icon" %>
															<p class="likes-number"> <%= article.likes.length%> </p>
														</div>
													<% end %>
													<br>
												<% end %>
											<% else %>
												<%= link_to like_path(:comment => article, :id => @test.id) ,:method => :delete do   %>
													<div class="d-flex likes-container">
													<%= image_tag "Liked.png", class: "like-icon" %>
														<p class="likes-number"> <%= article.likes.length%> </p>
													</div>
												<% end %>
												<br>
											<% end %>
										</div>
									</div>


								<% end %>
							</div>
						</div>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="pages-container">
  <div class="space-bg">
    <div class="news-container">
      <h1 class="page-title text-center">
        New article
      </h1>
      <div class="d-flex justify-content-center">
        <div class="ttm-card-bg edit-user-card d-flex justify-content-center">
          <%= form_tag url_for(action: "create"), method: "post", multipart: true do %>
            <div class="form-group">
              <%= label_tag 'Title' %><br />
              <%= text_field_tag 'title', "", class: "form-control"%>
            </div>
            <div class="form-group">
              <%= label_tag 'Content' %>  <br>
              <%= text_area_tag 'content', "", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= label_tag 'Tag' %>  <br>
              <%= text_field_tag 'tag', "", class: "form-control" %>
            </div>

              <%= file_field_tag :picture, class: "image-upload-container" %>

            <div class="actions d-flex justify-content-center">
              <%= submit_tag "Create article", class: "btn sign-ttm-btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="pages-container">
	<div class="space-bg">
		<div class="news-container">
			<div class="ttm-card-bg article-cards d-flex justify-content-between article-show-container">
				<div class="article-show-comment-container">
					<div class="article-show-card-container">
						<h3><%= @article.title %></h3>
						<hr class="articles-show-card-hr" align="left">
						<p class="article-user"><%= link_to @article.user.email, profile_path(@article.user) %></p>
						<p class=""><%= @article.content %></p>
						<div class="d-flex tags-container">
							<p class="tags"><%= @tag.name %></p>
						</div>
						<% if current_user%>

						<div class="d-flex">
							<div class="likes-container-container">
								<% @test = current_user.likes.find_by(article: @article) %>
								<% unless @test %>
									<% if @article.likes.length == 0 %>
										<%= link_to likes_path(:article => @article.id), :method => :post do %>
											<div class="d-flex likes-container">
											<%= image_tag "Like.png", class: "like-icon" %>
												<p class="likes-number"> 0 </p>
											</div>
										<% end %>
										<br>
									<% else %>
										<%= link_to likes_path(:article => @article.id), :method => :post do %>
											<div class="d-flex likes-container">
											<%= image_tag "Like.png", class: "like-icon" %>
												<p class="likes-number"> <%= @article.likes.length%> </p>
											</div>
										<% end %>
										<br>
									<% end %>
								<% else %>
									<%= link_to like_path(:comment => @article, :id => @test.id) ,:method => :delete do   %>
										<div class="d-flex likes-container">
										<%= image_tag "Liked.png", class: "like-icon" %>
											<p class="likes-number"> <%= @article.likes.length%> </p>
										</div>
									<% end %>
									<br>
								<% end %>
							</div>

							<div>
								<div id="favorite">
											<% unless current_user.favorite_articles.include? @article %>
													<a id="add"
														<%= link_to "OO", favorites_path(:article => @article.id), :method => :post, remote: true %>

														<%= image_tag "not-favorite.png", class: "like-icon favorite-icon" %>

													<a><br>
											<% else %>
													<a id="withdraw"<%= link_to "OO", favorite_path(:article => @article.id), :method => :delete, remote: true %>

														<%= image_tag "favorite.png", class: "like-icon favorite-icon" %>

													<a>
													<br>
											<% end %>
										</div>


									<% if current_user == @user %>
										<div class="article-btn-container">
											<a class="btn ttm-btn comment-btn your-article-btn"
												<%= link_to "Edit article", edit_article_path(@article.id) %>
											</a>
											<a class="btn ttm-btn comment-btn your-article-btn"
												<%= link_to "Delete article", article_path, :method => :delete %>
											</a>
										</div>
									<% end %>

								</div>
							</div>
						</div>

						<div class="post-comment-form-container">

							<%= form_tag comments_path, method: "post", class: "d-flex align-items-end" do %>
								<%= text_area_tag 'content','',class: "post-comment-text-area" %>
								<%= hidden_field_tag "article", @article.id %>
							  	<%= submit_tag "Comment", class: "btn sign-ttm-btn post-comment-btn" %>
							<% end %>
						</div>

					<% end %>
					<% if current_user %>
						<% unless @comments == nil %>
							<% @comments.each do |comment| %>
								<div class="comment-container">
									<div class="d-flex">
										<p class="comment-user"><%= comment.user.email %></p>
										<p class="comment-date"><%= comment.created_at %>
									</div>
									<hr class="comment-hr" align="left">
									<p class="comment-content"><%= comment.content %></p>

									<div class="comment-likes-container">
										<% unless current_user.likes.find_by(comment: comment) %>
											<% if comment.likes.length == 0 %>
												<%= link_to likes_path(:comment => comment.id, :article => @article.id), :method => :post do %>
												<div class="d-flex likes-container">
													<%= image_tag "Like.png", class: "like-icon" %>
													<p class="likes-number"> 0 </p>
												</div>
												<% end %>
												<br>
											<% else %>
												<%= link_to likes_path(:comment => comment.id, :article => @article.id), :method => :post do %>
												<div class="d-flex likes-container">
													<%= image_tag "Like.png", class: "like-icon" %>
													<p class="likes-number"> <%= comment.likes.length%> </p>
												</div>
												<% end %>
												<br>
											<% end %>
										<% else %>
											<%= link_to like_path(:comment => comment.id, :article => @article.id) ,:method => :delete do   %>
											<div class="d-flex likes-container">
												<%= image_tag "Liked.png", class: "like-icon" %>
												<p class="likes-number"> <%= comment.likes.length%> </p>
											</div>
											<% end %>
											<br>
										<% end %>
									</div>
									<% if current_user == comment.user %>
										<div class="comment-btn-container d-flex">
											<a class="btn ttm-btn comment-btn"
												<%= link_to "Edit comment", edit_comment_path(comment.id) %>
											</a>
											<a class="btn ttm-btn comment-btn"
												<%= link_to "Delete comment", comment_path(comment.id), :method => :delete %>
											</a>
										</div>
									<% end %>
								</div>
							<% end %>
						<% end %>
					<% end %>
				</div>
				<div class="article-show-img-container">
					<%= image_tag(@article.picture, class: "article-show-img") if @article.picture.attached? %>
				</div>
			</div>
		</div>
	</div>
</div>