config/routes.rb
Rails.application.routes.draw do

  resources :favorites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  root to: 'home#index'

  devise_for :users

  resources :user_cryptos
  resources :crypto_currencies, only: [:show]
  resources :cryptolist, only: [:show]

  resources :friend_requests, only: [:create]
  resources :friendships, only: [:create, :destroy]
  resources :profiles, only: [:index, :show, :update]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:show]
  resources :home, only: [:index]

  resources :news, only: [:index]
  resources :articles do
    resources :pictures, only: [:create]
  end
  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :admin, only: [:index, :show]


  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/terms_and_conditions'
  get 'static_pages/privacy_policy'

end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :user
	belongs_to :interlocutor, class_name: "User"
	has_many :messages
	
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def show
		 if Conversation.exists?(id: params[:id])

			@conversation = Conversation.find(params[:id])
			@messages = @conversation.messages
			Message.has_been_read?(@messages)
  	else
			id = params[:id].to_i
			id -= 1
			@conversation = Conversation.find(id)

			@messages = @conversation.messages
			Message.has_been_read?(@messages)
		end
	end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="pages-container">
	<div class="space-bg">
		<div class="news-container">
			<h1 class="page-title text-center">
				<%= Conversation %>
			</h1>
			<div class="d-flex justify-content-center">
				<div class="ttm-card-bg conv-card">
					<div class="form">
						<%= form_tag(messages_path, method: :post, class: "form", remote: true) do %>
								<label for="content">New Message<br>
							  <%= text_area_tag 'content',"", class: "post-comment-text-area" %><br>
							  <%= hidden_field_tag "recipient", @conversation.interlocutor.id %>
								<%= hidden_field_tag "id", @conversation.id %>
							  <%= submit_tag "Send Message",class: "btn sign-ttm-btn send-msg-btn", :name => 'commit' %>
						<% end %>
					</div>
					<ul id="message-list">
						<div class="d-flex flex-column">
							<% @messages.reverse.each do |message| %>
									<% if message.sender.email == current_user.email %>
										<div class="conv-msg-container-you">
											<li class="conv-msg-text conv-list">
												<p class="conv-msg-text conv-sender">
													You
												</p>
												<br>
												<p class="conv-msg-text">
													<%= message.content %>
												</p>
											</li>
										</div>
									<% else %>
										<div class="align-self-end conv-msg-container">
											<li class="conv-msg-text conv-list">
												<p class="conv-msg-text conv-sender">
													<%= message.sender.email %>
												</p>
												<br>
												<p class="conv-msg-text">
													<%= message.content %>
												</p>
											</li>
										</div>
									<% end %>
								<br/><br/>
							<% end %>
						</div>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>