config/routes.rb
Rails.application.routes.draw do

  resources :favorites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  root to: 'home#index'

  devise_for :users

  resources :user_cryptos
  resources :crypto_currencies, only: [:show]
  resources :cryptolist, only: [:show]

  resources :friend_requests, only: [:create]
  resources :friendships, only: [:create, :destroy]
  resources :profiles, only: [:index, :show, :update]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:show]
  resources :home, only: [:index]

  resources :news, only: [:index]
  resources :articles do
    resources :pictures, only: [:create]
  end
  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :admin, only: [:index, :show]


  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/terms_and_conditions'
  get 'static_pages/privacy_policy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="pages-container">
  <div class="space-bg">

    <div class="index-jumbotron">
      <div class="index-jumbotron-title">
        <h1 class="index-jumbotron-title-small">The most accessible</h1>
        <h1 class="index-jumbotron-title-big"><b>cryptocurrency toolkit</b></h1>
        <h1 class="index-jumbotron-title-small">in the universe</h1>
      </div>
      <%= image_tag("home/to-the-moon-index-main.png", class: "index-jumbotron-img", alt: "to-the-moon-homepage-main") %>
    </div>

    <div class="index-jumbotron-mobile">
      <div class="index-jumbotron-title-mobile">
        <h1 class="index-jumbotron-title-small-mobile">The most accessible</h1>
        <h1 class="index-jumbotron-title-big-mobile"><b>cryptocurrency<br/>toolkit</b></h1>
        <h1 class="index-jumbotron-title-small-mobile">in the universe</h1>
      </div>
      <%= image_tag("home/to-the-moon-index-main-mobile.png", class: "index-jumbotron-img", alt: "to-the-moon-homepage-main") %>
    </div>

    <div class="index-two-cards d-flex justify-content-center">
      <div class="index-cards-container-row">

        <div class="d-flex index-cards-container justify-content-center">
          <%= image_tag("home/To-the-Moon-homepage-Presentation.png", class: "index-cards-img", alt: "to-the-moon-homepage-presentation-telescope") %>

          <div class="ttm-card-bg index-card">
            <h2 class="index-card-title">Prepare your ride !</h2>

            <hr align="left" class="index-card-hr">

            <p class="index-card-text-bold">
            Follow your investments, invest fake coins to test your skills,
            </br>
            keep up-to-date and share it all with friends !
            </p>

            <p class="index-card-text">
            Our platform is designed as a tool-kit for cryptocurrencies investors who wants to get more knowledgeable on the crypto-market.
            </br>
            To the moon show you real-time prices from 1000+ cryptos projects, allows you to make previsions, gives you latest news, set up alerts on targeted cryptos prices and provides basic tools like exchanges prices and conversion.
            </p>

            <div class="d-flex">
              <% unless current_user %>
                <%= link_to '/users/sign_up' do %>
                  <div class="ttm-btn">Sign Up</div>
                <% end %>
              <% end %>
              <%= link_to '/static_pages/about' do %>
                <div class="ttm-btn">About Us</div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="index-cards-container-row-alt">

        <div class="d-flex index-cards-container-alt justify-content-center">
          <%= image_tag("home/To-the-Moon-homepage-Portfolio.png", class: "index-cards-img", alt: "to-the-moon-homepage-presentation-telescope") %>

          <div class="ttm-card-bg index-card">
            <h2 class="index-card-title">To the Moon Portfolio</h2>

            <hr align="left" class="index-card-hr">

            <p class="index-card-text-p">
            Here you will be able to follow evolution of targeted cryptos, visualise your portfolio evolution in real time, find articles, and much more !
            In short, the main tools are:
            </p>

            <p class="index-card-text-bold-p index-card-text-bold-n">
            - Real time price for more thant 1000 Cryptos.</br>
            - Chart evolution</br>
            - Currency converter</br>
            - Market cap
            </p>

            <div class="d-flex">
                <a class="ttm-btn"<%= link_to 'Portfolio', user_cryptos_path %></a>
          </div>
          </div>
        </div>
      </div>

    <div class="index-two-cards d-flex justify-content-center">
      <div class="index-cards-container-row">

        <div class="d-flex index-cards-container justify-content-center">
          <%= image_tag("home/To-the-Moon-homepage-News.png", class: "index-cards-img", alt: "to-the-moon-homepage-presentation-telescope") %>

          <div class="ttm-card-bg index-card">
            <h2 class="index-card-title">Our news feed</h2>

            <hr align="left" class="index-card-hr">

            <p class="index-card-text-bold-n">
            Find latest news on the crypto market, introduction of new Cryptos, and all other Crypto-related news.
            You'll also be able to target news based on your portfolio of Crypto currencies.
            </p>

            <div class="d-flex">
              <a class="ttm-btn"<%= link_to 'News', news_index_path %></a>
            </div>
          </div>
        </div>
      </div>

      <div class="index-cards-container-row-alt">

        <div class="d-flex index-cards-container-alt justify-content-center">
          <%= image_tag("home/To-the-Moon-homepage-Articles.png", class: "index-cards-img", alt: "to-the-moon-homepage-presentation-telescope") %>

          <div class="ttm-card-bg index-card">
            <h2 class="index-card-title">The community articles</h2>

            <hr align="left" class="index-card-hr">

            <p class="index-card-text-bold">
            Everyone can post its analysis on cryptos, the market in general, and engage into more specific talks.
            </p>

            <p class="index-card-text">
            This section is a real asset for your understanding of distributed ledger technology and the evolution of the Crypto world.
            </p>

              <div class="pond2 ">
                <div>  <%= image_tag("home/write.png", class: "index-cards-img2 ", alt: "to-the-moon-homepage-presentation-telescope") %>
                <h4 class="">Write your post</h4></div>
                <div>  <%= image_tag("home/comment.png", class: "index-cards-img2", alt: "to-the-moon-homepage-presentation-telescope") %>
                  <h4 class="index-card-text-bold2 ">Comment on </h4>
                  <h4 class="index-card-text-bold2 ">community posts</h4></div>
                <div>  <%= image_tag("home/star.png", class: "index-cards-img2", alt: "to-the-moon-homepage-presentation-telescope") %>
                  <h4 class="index-card-text-bold2 ">Save your</h4>
                  <h4 class="index-card-text-bold2 ">favourite posts</h4></div>
              </div>

              <div class="d-flex">
                <a class="ttm-btn"<%= link_to 'Articles', articles_path %></a>
              </div>
            </div>
          </div>


        </div>
      </div>

    <div class="index-two-cards d-flex justify-content-center index-last-cards">
      <div class="index-cards-container-row">

        <div class="d-flex index-cards-container justify-content-center">
          <%= image_tag("home/To-the-Moon-homepage-Comunity.png", class: "index-cards-img", alt: "to-the-moon-homepage-presentation-telescope") %>

          <div class="ttm-card-bg index-card">
            <h2 class="index-card-title">Social interractions in space</h2>

            <hr align="left" class="index-card-hr">

            <p class="index-card-text-bold-n">
            Here you are, like the kitchen in a house, this section is probably the most interesting one in the app because it allows you to interract with your peers, engage in talks on specific subjects or learn new previsions and strategies.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>